var LchColorWheel=function(){"use strict"
const t=(t,e,h)=>{const i=t.appendChild(document.createElement(e))
for(const t of Object.keys(h))i.style[t]=h[t]
return i}
class e{constructor(h){this.options=h,this.wheelDiameter=this.options.wheelDiameter||e.defaultOptions.wheelDiameter,this.wheelThickness=this.options.wheelThickness||e.defaultOptions.wheelThickness,this.handleDiameter=this.options.handleDiameter||e.defaultOptions.handleDiameter,this.maxChroma=this.options.maxChroma||e.defaultOptions.maxChroma,this.onChange=this.options.onChange||e.defaultOptions.onChange,this.rootElement=t(this.options.appendTo,"div",{position:"relative",borderRadius:"50%",display:"inline-block",lineHeight:"0",touchAction:"none",userSelect:"none",webkitTouchCallout:"none",webkitTapHighlightColor:"transparent"}),this.hueWheelElement=t(this.rootElement,"canvas",{borderRadius:"50%"}),this.hueHandleElement=t(this.rootElement,"div",{position:"absolute",boxSizing:"border-box",borderRadius:"50%",border:"2px solid white",boxShadow:"0 0 0 1px black inset",pointerEvents:"none"}),this.lcSpaceElement=t(this.rootElement,"canvas",{position:"absolute",left:"0",top:"0",right:"0",bottom:"0",margin:"auto"}),this.lcHandleElement=t(this.rootElement,"div",{position:"absolute",boxSizing:"border-box",borderRadius:"50%",border:"2px solid white",boxShadow:"0 0 0 1px black inset"}),this._rgb=[255,0,0],this._lch=e.rgb2lch(this._rgb),this._requestRedrawLcSpace_=!1,this.redraw(),this.hueWheelElement.addEventListener("pointerdown",t=>{if(0===t.button){const e=t.currentTarget
e.setPointerCapture(t.pointerId)
const h=Math.atan2(t.offsetY-e.height/2,t.offsetX-e.width/2)
this._setLch(this._lch[0],this._lch[1],180*h/Math.PI+90)}}),this.hueWheelElement.addEventListener("pointermove",t=>{const e=t.currentTarget
if(e.hasPointerCapture(t.pointerId)){const h=Math.atan2(t.offsetY-e.height/2,t.offsetX-e.width/2)
this._setLch(this._lch[0],this._lch[1],180*h/Math.PI+90)}}),this.lcSpaceElement.addEventListener("pointerdown",t=>{if(0===t.button){const e=t.currentTarget
e.setPointerCapture(t.pointerId),this._setLch(100-100*t.offsetY/e.width,t.offsetX*this.maxChroma/e.height,this._lch[2])}}),this.lcSpaceElement.addEventListener("pointermove",t=>{const e=t.currentTarget
e.hasPointerCapture(t.pointerId)&&this._setLch(100-100*t.offsetY/e.width,t.offsetX*this.maxChroma/e.height,this._lch[2])}),this.lcHandleElement.addEventListener("pointerdown",t=>{0===t.button&&this.lcSpaceElement.setPointerCapture(t.pointerId)})}get lch(){return this._lch}set lch(t){this._setLch(t[0],t[1],t[2])}get rgb(){return this._rgb}set rgb(t){this._setLch.apply(this,e.rgb2lch(t))}_setLch(t,h,i){const s=[...this._lch],a=this._lch=[Math.max(0,Math.min(100,t)),Math.max(0,Math.min(this.maxChroma,h)),i%360+(i<0?360:0)]
if(a[0]===s[0]&&a[1]===s[1]||(this._redrawLcHandle(),this._redrawHueWheel()),a[2]!==s[2]&&(this._redrawHueHandle(),this._requestRedrawLcSpace()),a[0]!==s[0]||a[1]!==s[1]||a[2]!==s[2]){const t=e.lch2rgb(this._lch)
this._rgb=[Math.round(t[0]),Math.round(t[1]),Math.round(t[2])],this.onChange(this)}}redraw(){this.hueWheelElement.width=this.hueWheelElement.height=this.wheelDiameter,this.lcSpaceElement.width=this.lcSpaceElement.height=(this.wheelDiameter-2*this.wheelThickness)*Math.SQRT1_2,this.hueHandleElement.style.width=this.hueHandleElement.style.height=this.lcHandleElement.style.width=this.lcHandleElement.style.height=this.handleDiameter+"px",this._redrawHueWheel(),this._redrawHueHandle(),this._redrawLcSpace(),this._redrawLcHandle()}_redrawHueWheel(){const[t,h]=this._lch,i=this.hueWheelElement,s=i.getContext("2d")
s.imageSmoothingEnabled=!1,s.lineWidth=this.wheelThickness,s.clearRect(0,0,i.width,i.height)
const a=i.width/2,n=i.height/2,o=a-this.wheelThickness/2,r=Math.PI/180
for(let i=0;i<360;i++){const l=e.lch2rgb([t,h,i])
s.beginPath(),s.arc(a,n,o,(i-90.5)*r,(i-89.2)*r),s.strokeStyle=`rgb(${l[0]},${l[1]},${l[2]})`,s.stroke()}}_redrawHueHandle(){const t=this.hueHandleElement.style,e=this.wheelDiameter/2,h=e-this.wheelThickness/2,i=(this._lch[2]-90)*Math.PI/180,s=-this.handleDiameter/2
t.left=h*Math.cos(i)+e+s+"px",t.top=h*Math.sin(i)+e+s+"px"}_redrawLcSpace(){const t=this._lch[2],h=this.lcSpaceElement,i=h.getContext("2d")
i.imageSmoothingEnabled=!1
const s=i.createImageData(h.width,h.height),a=s.data
let n=0
for(let h=0;h<s.height;h++)for(let i=0;i<s.width;i++)a.set(e.lch2rgb([100*(s.height-h)/s.height,i*this.maxChroma/s.width,t]),n),a[n+3]=255,n+=4
i.putImageData(s,0,0)}_redrawLcHandle(){const t=this.lcSpaceElement,e=this.lcHandleElement.style,h=-this.handleDiameter/2
e.top=t.offsetTop+t.offsetHeight*(1-this._lch[0]/100)+h+"px",e.left=t.offsetLeft+t.offsetWidth*this._lch[1]/this.maxChroma+h+"px"}_requestRedrawLcSpace(){this._requestRedrawLcSpace_||(this._requestRedrawLcSpace_=!0,requestAnimationFrame(()=>{this._requestRedrawLcSpace_=!1,this._redrawLcSpace()}))}}return e.defaultOptions={wheelDiameter:200,wheelThickness:20,handleDiameter:16,maxChroma:134,onChange:Function.prototype},e.lch2rgb=t=>{return function(t){var e,h,i,s=t[0]/100,a=t[1]/100,n=t[2]/100
return h=-.9689*s+1.8758*a+.0415*n,i=.0557*s+-.204*a+1.057*n,e=(e=3.2406*s+-1.5372*a+-.4986*n)>.0031308?1.055*Math.pow(e,1/2.4)-.055:e*=12.92,h=h>.0031308?1.055*Math.pow(h,1/2.4)-.055:h*=12.92,i=i>.0031308?1.055*Math.pow(i,1/2.4)-.055:i*=12.92,[255*(e=Math.min(Math.max(0,e),1)),255*(h=Math.min(Math.max(0,h),1)),255*(i=Math.min(Math.max(0,i),1))]}((e=function(t){var e,h=t[0],i=t[1]
return e=t[2]/360*2*Math.PI,[h,i*Math.cos(e),i*Math.sin(e)]}(t),n=e[0],o=e[1],r=e[2],n<=8?a=(i=100*n/903.3)/100*7.787+16/116:(i=100*Math.pow((n+16)/116,3),a=Math.pow(i/100,1/3)),[h=h/95.047<=.008856?h=95.047*(o/500+a-16/116)/7.787:95.047*Math.pow(o/500+a,3),i,s=s/108.883<=.008859?s=108.883*(a-r/200-16/116)/7.787:108.883*Math.pow(a-r/200,3)]))
var e,h,i,s,a,n,o,r},e.rgb2lch=t=>{return n=function(t){var e=t[0]/255,h=t[1]/255,i=t[2]/255
return[100*(.4124*(e=e>.04045?Math.pow((e+.055)/1.055,2.4):e/12.92)+.3576*(h=h>.04045?Math.pow((h+.055)/1.055,2.4):h/12.92)+.1805*(i=i>.04045?Math.pow((i+.055)/1.055,2.4):i/12.92)),100*(.2126*e+.7152*h+.0722*i),100*(.0193*e+.1192*h+.9505*i)]}(t),o=n[0],r=n[1],l=n[2],r/=100,l/=108.883,o=(o/=95.047)>.008856?Math.pow(o,1/3):7.787*o+16/116,e=[116*(r=r>.008856?Math.pow(r,1/3):7.787*r+16/116)-16,500*(o-r),200*(r-(l=l>.008856?Math.pow(l,1/3):7.787*l+16/116))],i=e[0],s=e[1],a=e[2],(h=360*Math.atan2(a,s)/2/Math.PI)<0&&(h+=360),[i,Math.sqrt(s*s+a*a),h]
var e,h,i,s,a,n,o,r,l},e}()
